function getPoem(){
poem1 = [
'poema en forma de codigo ofuscado',
'',
'',
'           void',
'      setup() {',
'      size(640,',
'480);}  void', 
'      draw()  {', 
'      p();  }', 
'      void p(){',
'      background', 
'      (0);text(', 
'      "azul",70', 
'      ,10);frameRate(5);text(', 
'      "brillante",50,20);text("el Ojo el",',
'      50,30);text("pico anaranjado",8,40);for(int',
'      i=0;i<6;i++){text("el cuello",50',
'      ,50+i*10);}text("el cuello "+',
'      "herido",50,110);for(int i=',
'      0;i<20;i++){text("plumaje",random',
'      (50,170),120+i*3);}',
'             for(int',
'             i=0;i<8',
'             ;i++) {',
'             text  (',
'             "patas"',
'             ,85,190',
'             +i*10);',
'             } text(',
'             "patas"',
'             +" a mi"',
'             +" mesa",85,270);}'];
poem2 = [
'poema en forma de pajaro',
'',
'',
'           azul',
'      brillante',
'      el Ojo el',
'pico anaranjado', 
'      el cuello', 
'      el cuello', 
'      el cuello',
'      el cuello', 
'      el cuello', 
'      el cuello', 
'      el cuello herido', 
'      pajaro de papel y tinta que no vuela',
'      que no se mueve que no canta que no respira',
'      animal hecho de versos amarillos',
'      de silencioso plumaje impreso',
'      tal vez un soplo desbarata',
'      la misteriosa palabra que sujeta',
'      sus dos patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              patas',
'              a mi mesa'];
poem3 = [
'      e       i',
'             i',
'',      
'     i',
'a                o',     
'  i e         u',   
'             a',
'               o i',
'                i',
'',
'                    u',
'                  o',
'',
'                      a',
'',
'   (viento de vocales)'];

poem4 = [
'      *       *',
'             *',
'',      
'     *',
'*                *',     
'  * *         *',   
'             *',
'               * *',
'                *',
'',
'                    *',
'                  *',
'',
'                      *',
'',
'     (constelaciones)'];

poem5 = [
'                                 *',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'                    ~',
'               pequeno punto brillante como el sol'];

poem6 = [
'                                 *',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'',
'imagen de la Tierra a 6000 millones de km desde la sonda Voyager'];

poem7 = [
'		     	..',
'		     .0O1."',
'		     u$ON=1',
'		     z00BA|',
'		    |..=~.',
'	   	;s<"""',
'		   NRX~=-"',
'		   z0c.<X.',
'	   	%B0s%."',
'		    &&$H%',
'		   n$0=XN;."',
'	   iB8B0vU1=%"',
'	   "$&00cRr"vu|',
'		   FAHZuqr-',
'		   ZZUFA&FI."',
'	   ;BRHv n$U"-',
'	  "ARN1   "&si',
'	 "Onv%     O1.',
'	 cOqr      rs."',
'	 aUU"       ul"',
'	"RO-         :."',
'	nn%"         -=.~|-"',
'	=1.".."      ".."',
'',
'',
'"Thats one small step for a bot"'];
}